### ISSUE TITLE
Todo: Multidimensional benchmarks.

### ISSUE THREAD

**Issue by gabrielfougeron** [gabrielfougeron/pyquickbench#2]
role of all_sizes ?
run_benchmark vs plot_benchmark ?

**Comment by gabrielfougeron** [comment]
all_sizes becomes a dictionnary ?

**Comment by gabrielfougeron** [comment]
Options for plotting a dimension of all_args

- [x] single value (ignore all but one value)
- [x] Same (do not change plot style)
- [x] Points (exactly one required)
- [x] Curve color
- [x] Curve linestyle
- [x] Curve pointstyle
- [x] Subplot grid x/y
- [x] General ax
- [x] avg reduction
